add loadapp func to my bash rc file

diff --git a/dotfiles/bashrc b/dotfiles/bashrc
--- a/dotfiles/bashrc
+++ b/dotfiles/bashrc
@@ -65,6 +65,34 @@ lanl-unproxify() {
 }
 
 ################################################################################
+# convenience functions
+################################################################################
+# sets PATH and LD_LIBRARY_PATH for a specified dir
+loadapp()
+{
+    if [[ $# == 1 ]]; then
+        basedir="$1"
+        if [[ ! -d "$basedir" || ! -d "$basedir/bin" || ! -d "$basedir/lib" ]];
+        then
+            echo "cannot use: $basedir"
+            return 1
+        fi
+        pushd "$basedir" 2>&1 > /dev/null
+        if [[ $? != 0 ]]; then
+            echo "pushd failure..."
+            return 1
+        fi
+        abs_path=`pwd`
+        popd 2>&1 > /dev/null
+        PATH=$abs_path/bin:$PATH
+        export LD_LIBRARY_PATH=$abs_path/lib:$LD_LIBRARY_PATH
+    else
+        echo "usage: loadapp /path/to/app"
+        return 1
+    fi
+}
+
+################################################################################
 # aliases
 ################################################################################
 # repo checkout
